### ISSUE TITLE
Troubles with TAP driver certificate

### ISSUE THREAD

**Issue by jupsoleil** [wget/chocolatey_openvpn#6]
Silent install not possible for the time being.

**Comment by wget** [comment]
@jupsoleil Thanks. The problem has been fixed. A new package revision has been pushed to chocolatey.

**Comment by jupsoleil** [comment]
Hi, i'm sorry, but still not fixed.  I now get the error (a pop-up window, when launching the upgrade from command line):

'TAP-Windows 9.22.1-I601 Setup
An error occurred installing the TAP device driver.'

https://openvpn.net/index.php/open-source/downloads.html still lists tap-windows-9.21.2.exe .

**Comment by wget** [comment]
What was the previous version you had installed?

You meant the issue could happen for people having installed the OpenVPN package 2.4.6, but are upgrading to 2.4.6.20180710?

**Comment by wget** [comment]
@jupsoleil Any news from this?

If I don't have any news from you by the end of this week, I'll consider the issue as not applicable and close it.

**Comment by wget** [comment]
Closing since no news + the fact the package has been installed by 50 K users on chocolatey.

**Comment by jupsoleil** [comment]
Sorry I missed the last mail about this issue. 
I didn't see this appear anymore on other systems so OK indeed.
